CC=gcc
CXX=g++
RM=rm -f
CPPFLAGS=-fopenmp

SRCS=bitmap_image.cpp, image_handler.cpp, mandel_plotter.cpp, window.cpp, main.cpp
OBJS=$(subst .cpp,.o,$(SRCS))

mandel: $(OBJS)
    g++ -o bitmap_image.o image_handler.o mandel_plotter.o main.o 

bitmap_image.o: bitmap_image.cpp bitmap_image.hpp 
    g++ $(CPPFLAGS) -c bitmap_image.cpp -o bitmap_image.o

image_handler.o: image_handler.cpp image_handler.hpp window.hpp 
    g++ $(CPPFLAGS) -c image_handler.cpp -o image_handler.o
	
mandel_plotter.o: mandel_plotter.cpp mandel_plotter.hpp window.hpp
    g++ $(CPPFLAGS) -c mandel_plotter.cpp -o mandel_plotter.o
	
main.o: main.cpp
	g++ $(CPPFLAGS) -c main.cpp -o main.o